[project]
name = "sb2gs"
version = "2.0.0"
description = "sb2gs is the goboscript decompiler."
authors = [{ name = "aspizu", email = "aspizu@protonmail.com" }]
dependencies = []
readme = "README.md"
requires-python = ">= 3.13.1"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "rich>=13.9.4",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/sb2gs"]
